### ISSUE TITLE
ValueError: Cannot end root section; openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by mkrupczak3** [irgolic/AutoPR#118]
AutoPR is configured correctly, however it doesn't seem to be using the openai API properly:

[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/Theta-Limited/OpenAthenaAndroid/actions/runs/5638217973)

AutoPR encountered an error.  
Issue: https://github.com/Theta-Limited/OpenAthenaAndroid/issues/78  
Pull Request: https://github.com/Theta-Limited/OpenAthenaAndroid/pull/83

## Traceback

```
Traceback (most recent call last):
  File "/app/autopr/services/action_service.py", line 186, in run_action
    results = action.run(arguments, context)
  File "/app/autopr/actions/look_at_files.py", line 375, in run
    filepaths = self.get_initial_filepaths(files, context)
  File "/app/autopr/actions/look_at_files.py", line 276, in get_initial_filepaths
    response = self.rail_service.run_prompt_rail(
  File "/app/autopr/services/rail_service.py", line 355, in run_prompt_rail
    prompt = self.completions_repo.complete(
  File "/app/autopr/repos/completions_repo.py", line 84, in complete
    raise e
  File "/app/autopr/repos/completions_repo.py", line 65, in complete
    result = self._complete(
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/app/autopr/repos/completions_repo.py", line 142, in _complete
    openai_response = openai.ChatCompletion.create(
  File "/venv/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/autopr/services/agent_service.py", line 78, in run_agent
    agent.handle_event(event)
  File "/app/autopr/agents/plan_and_code.py", line 216, in handle_event
    self.create_pull_request(event)
  File "/app/autopr/agents/plan_and_code.py", line 176, in create_pull_request
    context = self.action_service.run_actions_iteratively(
  File "/app/autopr/services/action_service.py", line 215, in run_actions_iteratively
    context = self.run_action(action_id, context)
  File "/app/autopr/services/action_service.py", line 195, in run_action
    self.publish_service.end_section(f"❌ Failed {action_id}")
  File "/app/autopr/services/publish_service.py", line 237, in end_section
    raise ValueError("Cannot end root section")
ValueError: Cannot end root section

```

**Comment by mkrupczak3** [comment]
I am using this with a valid API key, and I have verified my OpenAI account is able to use the gpt-4 API

**Comment by irgolic** [comment]
Hey, thanks for the issue. You're right, GPT-4 is now generally available, not sure why this is occuring. I'll look into it tomorrow :)

**Comment by irgolic** [comment]
I don't have a way to test this out actually. I only have one account with GPT-4 access right now, which works for me.

https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

Supposedly they've only granted GPT-4 access to those who have spent at least $1 on their API. I tried running it with the API key of my other account, which does not have access, and got the same error as you. 

Are you sure your API key is able to access GPT-4 API? Can you try running a small python script with it? 

```python
import openai
openai.api_key = ...
openai.ChatCompletion.create(
  model="gpt-4",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ]
```
)

**Comment by mkrupczak3** [comment]
Ok, it seems my API key is not working then. I get the same error using my API key with the test script you provided.

I'm a ChatGPT plus subscriber and have spent at least $2.54 on the gpt-3.5-turbo API this month:

<img width="799" alt="Screenshot 2023-07-25 at 1 11 02 PM" src="https://github.com/irgolic/AutoPR/assets/25494111/08823f17-ee4f-4b93-9dd8-72c60727d2dc">

This is an issue I'll have to bring up with OpenAI's support team. This issue can be closed
