### ISSUE TITLE
KeyError: 'edit_file'

### ISSUE THREAD

**Issue by joglr** [irgolic/AutoPR#66]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/joglr/klods/actions/runs/4846163955)

AutoPR encountered an error while trying to fix https://github.com/joglr/klods/issues/29.

## Traceback

```
Traceback (most recent call last):
  File "/app/autopr/agents/brain_agent/base.py", line 64, in generate_pr
    self._generate_pr(event)
  File "/app/autopr/agents/brain_agent/simple_v1.py", line 34, in _generate_pr
    self.codegen_agent.generate_changes(
  File "/app/autopr/agents/codegen_agent/base.py", line 54, in generate_changes
    self._generate_changes(repo, issue, pr_desc, current_commit)
  File "/app/autopr/agents/codegen_agent/autonomous_v1/agent.py", line 320, in _generate_changes
    action = self.rail_service.run_prompt_rail(action_rail)
  File "/app/autopr/services/rail_service.py", line 205, in run_prompt_rail
    return self.run_rail_object(rail.output_type, prompt)
  File "/app/autopr/services/rail_service.py", line 124, in run_rail_object
    raw_o, dict_o = pr_guard(
  File "/venv/lib/python3.9/site-packages/guardrails/guard.py", line 144, in __call__
    guard_history = runner(prompt_params=prompt_params)
  File "/venv/lib/python3.9/site-packages/guardrails/run.py", line 89, in __call__
    validated_output, reasks = self.step(
  File "/venv/lib/python3.9/site-packages/guardrails/run.py", line 145, in step
    validated_output = self.validate(index, output_as_dict, output_schema)
  File "/venv/lib/python3.9/site-packages/guardrails/run.py", line 262, in validate
    validated_output = output_schema.validate(output_as_dict)
  File "/venv/lib/python3.9/site-packages/guardrails/schema.py", line 328, in validate
    validated_response = self[field].validate(
  File "/venv/lib/python3.9/site-packages/guardrails/datatypes.py", line 344, in validate
    selected_value = schema[selected_key]
KeyError: 'edit_file'

```

**Comment by irgolic** [comment]
Hi @joglr, thanks for trying out AutoPR.

This crash is due to a bug in guardrails, I've submitted a fix that avoids throwing this error in https://github.com/ShreyaR/guardrails/pull/123.

Although, AutoPR code generation is currently not optimized for `gpt-3.5-turbo`. See https://github.com/irgolic/AutoPR/issues/65 for more details. If you have access to the `gpt-4` API please use that instead. In the mean time, I'll add a warning linking to the issue if you're using `gpt-3.5-turbo`.
