### ISSUE TITLE
JSONDecodeError in action

### ISSUE THREAD

**Issue by L4legenda** [irgolic/AutoPR#73]
https://github.com/L4legenda/test_auto_pr/actions/runs/4884170663/jobs/8716528416

Downloading (…)olve/main/vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 1.04M/1.04M [00:00<00:00, 6.35MB/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 1.04M/1.04M [00:00<00:00, 6.28MB/s]

Downloading (…)olve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 2.53MB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 2.51MB/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 1.36M/1.36M [00:00<00:00, 7.44MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 1.36M/1.36M [00:00<00:00, 7.34MB/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]
Downloading (…)lve/main/config.json: 100%|██████████| 665/665 [00:00<00:00, 209kB/s]
Creating new branch autopr/1... service=commit
Removing guardrails.log...     service=commit
Committed changes              commit_message=[empty] diff= service=commit
Pushing branch autopr/1 to remote... service=commit
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line [19](https://github.com/L4legenda/test_auto_pr/actions/runs/4884170663/jobs/8716528416#step:6:20)7, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/autopr/gh_actions_entrypoint.py", line 94, in <module>
    main(
  File "/app/autopr/main.py", line 135, in main
    brain_agent.generate_pr(event)
  File "/app/autopr/agents/brain_agent/base.py", line 60, in generate_pr
    self.publish_service.update()
  File "/app/autopr/services/publish_service.py", line 346, in update
    self._publish(title, body)
  File "/app/autopr/services/publish_service.py", line 445, in _publish
    self._create_pr(title, body, success)
  File "/app/autopr/services/publish_service.py", line 467, in _create_pr
    if self._is_draft_error(response.text):
  File "/app/autopr/services/publish_service.py", line 481, in _is_draft_error
    response_obj = json.loads(response_text)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line [35](https://github.com/L4legenda/test_auto_pr/actions/runs/4884170663/jobs/8716528416#step:6:36)5, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by irgolic** [comment]
Thanks for the issue.

The problem comes from the JSON parsing code on `autopr/services/publish_service.py:481`, it should be wrapped in a try/except and return False if the text isn't decodable.

**Comment by irgolic** [comment]
Fixed by #108
