### ISSUE TITLE
Invalid patch?

### ISSUE THREAD

**Issue by acheong08** [irgolic/AutoPR#8]
```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/github/workspace/autopr/gh_actions_entrypoint.py", line 18, in <module>
    main(
  File "/github/workspace/autopr/main.py", line 46, in main
    pr = generator.generate_pr(tree, issue_title, issue_body, issue_number)
  File "/github/workspace/autopr/services/generation_service.py", line 238, in generate_pr
    pr_model = self._generate_pr(codebase, issue_text)
  File "/github/workspace/autopr/services/generation_service.py", line 181, in _generate_pr
    raw_o, dict_o = pr_guard(
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/guardrails.py", line 101, in __call__
    return self.ask_with_validation(prompt, llm_ask, num_reasks)
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/guardrails.py", line 108, in ask_with_validation
    guard_history = self.validation_inner_loop(
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/guardrails.py", line 169, in validation_inner_loop
    validated_response, reasks = self.validate_output(
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/guardrails.py", line 239, in validate_output
    validated_response = schema[field].validate(
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/datatypes.py", line 299, in validate
    value = child_data_type.validate(
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/datatypes.py", line 259, in validate
    value = item_type.validate(i, item, value)
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/datatypes.py", line 299, in validate
    value = child_data_type.validate(
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/datatypes.py", line 126, in validate
    schema = validator.validate_with_correction(key, value, schema)
  File "/github/home/.cache/pypoetry/virtualenvs/autopr-cDQ_M3T8-py3.9/lib/python3.9/site-packages/guardrails/validators.py", line 196, in validate_with_correction
    return self.on_fail(e)
  File "/github/workspace/autopr/validators.py", line 239, in fix
    lines = remove_hallucinated_lines(lines, tree)
  File "/github/workspace/autopr/validators.py", line 108, in remove_hallucinated_lines
    check_file_line = current_file_content[check_line_number]
IndexError: list index out of range
```

**Comment by irgolic** [comment]
Fixed by #11
