### ISSUE TITLE
KeyError: 'edit_file'

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#95]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/deep-foundation/deepclient/actions/runs/4893182557)

AutoPR encountered an error while trying to fix https://github.com/deep-foundation/deepclient/issues/13.

## Traceback

```
Traceback (most recent call last):
  File "/app/autopr/agents/brain_agent/base.py", line 75, in generate_pr
    self._generate_pr(event)
  File "/app/autopr/agents/brain_agent/simple_v1.py", line 34, in _generate_pr
    self.codegen_agent.generate_changes(
  File "/app/autopr/agents/codegen_agent/base.py", line 54, in generate_changes
    self._generate_changes(repo, issue, pr_desc, current_commit)
  File "/app/autopr/agents/codegen_agent/autonomous_v1/agent.py", line 320, in _generate_changes
    action = self.rail_service.run_prompt_rail(action_rail)
  File "/app/autopr/services/rail_service.py", line 202, in run_prompt_rail
    return self.run_rail_object(rail.output_type, prompt)
  File "/app/autopr/services/rail_service.py", line 124, in run_rail_object
    raw_o, dict_o = pr_guard(
  File "/venv/lib/python3.9/site-packages/guardrails/guard.py", line 144, in __call__
    guard_history = runner(prompt_params=prompt_params)
  File "/venv/lib/python3.9/site-packages/guardrails/run.py", line 89, in __call__
    validated_output, reasks = self.step(
  File "/venv/lib/python3.9/site-packages/guardrails/run.py", line 145, in step
    validated_output = self.validate(index, output_as_dict, output_schema)
  File "/venv/lib/python3.9/site-packages/guardrails/run.py", line 262, in validate
    validated_output = output_schema.validate(output_as_dict)
  File "/venv/lib/python3.9/site-packages/guardrails/schema.py", line 328, in validate
    validated_response = self[field].validate(
  File "/venv/lib/python3.9/site-packages/guardrails/datatypes.py", line 344, in validate
    selected_value = schema[selected_key]
KeyError: 'edit_file'

```

**Comment by irgolic** [comment]
Wow, [GPT-4 made a mistake that I've only seen GPT-3.5-turbo make](https://github.com/deep-foundation/deepclient/actions/runs/4893182557/jobs/8735843656#step:6:3580).

It returned:
```json
{
  "action": "edit_file",
  "filepath": "deep_client_options.py",
  "description": "Add new fields with default values in the DeepClientOptions class and update the constructor to accept them as optional keyword arguments."
}
```

Instead of
```json
{
  "action": "edit_file",
  "edit_file": {
    "filepath": "deep_client_options.py",
    "description": "Add new fields with default values in the DeepClientOptions class and update the constructor to accept them as optional keyword arguments."
  }
}
```

This exception will be fixed when https://github.com/ShreyaR/guardrails/pull/123 is merged on the guardrails repo. Although there's potential for better handling – @ShreyaR's comments in that PR outline how we could catch and fix errors like this. If only the exception throwing fix gets merged (as https://github.com/ShreyaR/guardrails/pull/123 proposes now), we can also do a more naive fix in AutoPR.
